### ISSUE TITLE
Don't raise an exception on failure to CreateBucket

### ISSUE THREAD

**Issue by Eronarn** [RaRe-Technologies/smart_open#154]
```
Traceback (most recent call last):
  File "/opt/crash_uploader", line 165, in <module>
    upload_user_coredump(pid, executable)
  File "/opt/crash_uploader", line 123, in upload_user_coredump
    with smart_open(dumpfile, 'wb') as s3out:
  File "/usr/local/lib/python2.7/dist-packages/smart_open/smart_open_lib.py", line 175, in smart_open
    return s3_open_uri(parsed_uri, mode, **kw)
  File "/usr/local/lib/python2.7/dist-packages/smart_open/smart_open_lib.py", line 255, in s3_open_uri
    fobj = smart_open_s3.open(parsed_uri.bucket_id, parsed_uri.key_id, s3_mode, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/smart_open/s3.py", line 60, in open
    fileobj = BufferedOutputBase(bucket_id, key_id, min_part_size=s3_min_part_size, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/smart_open/s3.py", line 255, in __init__
    s3.create_bucket(Bucket=bucket)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied
```

In general implicit bucket creation seems like a bad call, in case of a misconfig. But if it is going to happen, it definitely shouldn't block writing to that bucket if it already exists. (In our case this is running from an IAM box that does not have permission to create buckets, but can write to an existing bucket.)

Testing indicates this broke in 1.5.4

**Comment by piskvorky** [comment]
Creating buckets by default would definitely be a bug, that's horrible, I agree.

@menshikh-iv what happened in 1.5.4?

**Comment by gdoron** [comment]
Hit it myself now.
Wasted 4 hours 😢 😢 😢 😢 😢

**Comment by jerluc** [comment]
Also ran into this. Is there any toggle for specifiying? Or should we just assume that it will always try to create a bucket? Just afraid of the typo scenario which would auto-create a bucket that shouldn't exist 😨

**Comment by piskvorky** [comment]
@menshikh-iv we need the bug fix release ASAP.

**Comment by menshikh-iv** [comment]
@piskvorky work on it, will release smart_open today

**Comment by andscoop** [comment]
@menshikh-iv @piskvorky  I don't believe this issue is resolved. I am still running into it in 1.5.5
 
According to the original error the issue is occurring on line 255 of s3.py.

`File "/usr/local/lib/python2.7/dist-packages/smart_open/s3.py", line 255, in __init__ s3.create_bucket(Bucket=bucket)`

Your fix applies to line ~286 of s3.py.

From here things get a little strange, I have been debugging and found that the error still occurs when running the program normally. But while debugging with VSC the error does not occur and the upload occurs as expected.

Context:
- s3 bucket exists
- IAM user has write permission but not permission to create_bucket
- program still attempts to create bucket at line 255 of s3.py in normal execution only. In debug mode issue does not occur.

This is a big blocker for me so I will be updating if I find anything, in the mean time any ideas are welcome.
