### ISSUE TITLE
S3 argument change in 1.8.1 is backwards-incompatible with 1.8.0

### ISSUE THREAD

**Issue by rtkamorozov** [RaRe-Technologies/smart_open#290]
First off, thanks for the wonderful library! It really saves us a lot of effort when streaming objects to/from S3.

I think it would be nice if you guys adopted the semver workflow from https://semver.org/. Namely, I would propose you bump the major version when making API-incompatible changes.
To give you an example - I've had the `smart_open` version pinned as `>=1.8.0,<2.0` to make sure I get all the fixes and updates within the current major version.

The recent update from `1.8.0` to `1.8.1` broke our service because the `s3.smart_open` switched from `s3_upload` argument to a `transport_params` dict. 
The issue manifested itself in a very subtle way (it didn't fail hard since it's a keyword argument) and was hard to pinpoint.

If you could bump the major version component each time backwards-incompatible changes are introduced, that would be amazing.

**Comment by mpenkov** [comment]
Thank you for the report. Glad you are finding the library helpful.

We are on board with the semantic versioning concept. One of our goals for 1.8.1 was to make maintain full backwards compatibility with 1.8.0. E.g. we intended the old smart_open.smart_open function to behave exactly as in 1.8.1. It sounds like we failed to meet that goal in your case, and that's something we'd like to fix moving forward.

Could you provide more info about what broke in your particular case? How were you calling smart_open, and how was the behavior different in 1.8.0 and 1.8.1? A reproducible example would be really helpful here.

Pinging @piskvorky because it's relevant.

**Comment by rtkamorozov** [comment]
Thanks for the prompt response, @mpenkov .
Sure, let' me elaborate on my use case.

I am using `smart_open` to create a large `tar.gz` archive and stream it to S3. The bucket I am uploading to requires server-side encryption, and I have been passing additional arguments to `open` like this:
```
    smart_open(
      's3://{bucket}/{key}'.format(bucket=self._bucket, key=self._key),
      'wb',
      s3_upload={
        'ServerSideEncryption': 'AES256'
      },
    )
```

During one of the builds, `smart_open` got upgraded and I started seeing cryptic "Access Denied" messages in the system test environment. Initially, I attributed that to the changeset that triggered the build but quickly realized it was not the case. After spending some time, I have identified the root cause.

New library version was (almost) silently dropping my `s3_upload` argument and thus attempting to do an unencrypted upload. My preference would be that the library should have either translated the arguments in a backwards-compatible way or failed loudly if it saw an old version of the argument. The latter option would imply a major semver bump as well.

I would be happy to clarify my use case further should you need that.

**Comment by mpenkov** [comment]
Thank you for providing details. We will investigate and release a bugfix that restores back compatibility.

I am sorry that this caused you inconvenience.

**Comment by rtkamorozov** [comment]
No worries, thanks for following up so quickly!
