### ISSUE TITLE
Feature Request: Add plugin support to enable new protocols

### ISSUE THREAD

**Issue by dargueta** [RaRe-Technologies/smart_open#440]
#### Problem description

I was thinking maybe we could provide a plugin system so that people can build their own packages and provide support for other file systems/protocols, (e.g. `dropbox://` to access a file on Dropbox) _without_ having to put all of them in `smart_open()` and make it a heavyweight package. For example, one could implement https://github.com/RaRe-Technologies/smart_open/issues/228 as a plugin so that we don't need to make everyone install the Azure Python client even if they're never going to use it.

There is prior art around this. `setuptools` supports entry points for [building plugins](https://packaging.python.org/guides/creating-and-discovering-plugins/), and we could use [pluggy](https://pypi.org/project/pluggy/) to provide hooks for recognizing and implementing file system protocols. [PyFilesystem2](https://pypi.org/project/fs/) does something very similar already so we could look there for inspiration.

**Comment by piskvorky** [comment]
Interesting idea, thanks.

I also like the badge in your link :) @mpenkov WDYT about adding these?
[![Downloads](https://pepy.tech/badge/smart-open/month)](https://pepy.tech/project/smart-open/month)
[![Downloads](https://pepy.tech/badge/gensim/month)](https://pepy.tech/project/gensim/month)

**Comment by mpenkov** [comment]
It's an interesting idea, but I don't think it's worth the effort at the moment, because it introduces additional complexity and doesn't solve any problems that are hurting us at the moment.

For example, if we started to get overwhelmed with dependencies like boto3, gcs, etc. (currently, it's manageable), then we could make them optional, like we do with `paramiko`.

If people were contributing backends faster than we could merge PRs (again, we're nowhere near that now) then it would make sense to think about plugins.

**Comment by dargueta** [comment]
Haha I already started tinkering with it. But yes, I do see your point.

**Comment by dargueta** [comment]
Gonna close this for now and we can revisit it later I guess

**Comment by piskvorky** [comment]
@dargueta you can open Dropbox as a PR  – that sounds useful!

**Comment by dargueta** [comment]
Will do
