### ISSUE TITLE
Make the submodule importing system robust to missing extras

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/smart_open#463]
I'm not sure about this but I think the imports in the code should now be in try except ? Like if someone installs the smart_open[gcs] the smart_open.s3 will throw an import error

_Originally posted by @Tyrannas in https://github.com/RaRe-Technologies/smart_open/pull/454#issuecomment-609804100_

**Comment by Amertz08** [comment]
I think for sure the `s3` module does. As there is more than 1 entry point into the module. There is the `register_transport` which catches an `ImportError` and thus if there is a `try/except` it would need to reraise the error so that the `register_transport` path still works. The 2nd being the `iter_bucket` function. As a consumer could import that without ever going down the `register_transport` path directly.

You could not have the catch there but at least imo it allows you to print an error message detailing the fix.
