### ISSUE TITLE
Add s3._list_bucket to public API

### ISSUE THREAD

**Issue by ddelange** [RaRe-Technologies/smart_open#692]
#### Problem description

Hi :wave:

I would like to iterate over a bucket, copying files *in-memory* using smart-open, and `smart_open.s3._list_bucket` is a perfect candidate to build upon. It would be awesome if it can be added to the public API and we can start to rely on it being available also in future versions!

Use-case for `_list_bucket`:

- Copy one huge s3 bucket to a new s3 bucket using a machine with very little memory/storage (where `smart_open.s3.iter_bucket` can't be used).
- Only copy files with a `.jsonl` extension, and writing them out as `.jsonl.gz` files. `_list_bucket` already has nice functionality available for this use-case!

Example:

```py
from typing import Iterator
from smart_open.s3 import _list_bucket

def list_file_paths(bucket: str, prefix: str, suffix: str = "") -> Iterator[str]:
    """List all files in an S3 bucket with certain prefix and optional suffix."""
    keys = _list_bucket(bucket, prefix, accept_key=lambda k: k.endswith(suffix))
    yield from (f"s3://{bucket}/{key}" for key in keys)
```

#### Steps/code to reproduce the problem

N/A

#### Versions

Please provide the output of:

```python
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.10 (default, Sep  1 2021, 10:14:33)
[Clang 12.0.0 (clang-1200.0.32.29)]
smart_open 5.2.1
```

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by mpenkov** [comment]
Sorry, this is out of scope for us.  Listing buckets is intentionally not part of our public API: it makes the abstraction that smart_open provides (streaming) more leaky than it really needs to be.

For your use case of copying buckets, using smart_open is _definitely_ a bad idea, because it streams the data from the source bucket to the destination bucket **through the machine running the code**. It's a giant bottleneck.

You're better of copying data between buckets directly (S3 supports this):

    aws s3 cp --recursive s3://source/foo s3://destination/foo
